### ISSUE TITLE
isPrime: for-loop with BigInteger

### ISSUE THREAD

**Issue by tnakai11** [nekokaeru/SE20#23]
Hello, I am Nakai. I am working on the branch 'tnakai'.

For avoiding overflow, I employed 'java.math.BigInteger' instead of 'Long'.
In the function 'isPrime(x: BigInteger)', I want to use for-loop for checking whether x has a divisor. However, I could not find a way to use iterators which yield BigInteger. 

Currently, I am using while-loop, but I think it is not so smart.
Does anyone has a good idea?

Thank you.

**Comment by ebrosset** [comment]
Hello, Edwin here.

Iterating over a big Integer might be a "trap idea", in the sense that a Long number already is quite big (max value is 2^63 -1). Iterating in a for loop from 1 to this maximum value might already be a difficult and time consuming task for a computer, because of the sheer amount of cases to review. For this reason, we can expect it to even less feasible to iterate from 1 to a bigInteger number, because the computer might take years to finish going through the loop. 

For this reason, I came to the conclusion that trying to fit a bigInterger inside the isPrime() function loop might not be the better solution. Instead, one interesting idea would be to do as 七井-san suggested in another issue : to do the loop from 1 to sqrt(n). This way, you can just have your loop upper bound within the Long type size, as long as we do not go to any number to 2^(64*2). All there is to to is to cast the upper size of the for loop to a long number.

**Comment by tnakai11** [comment]
Thank you, Edwin!
I was sticking to my idea.

**Comment by FGKN0263** [comment]
It takes so long time that you should take another way. 
But, If you add next code, you can use for loop with BigInteger.
Reference : https://stackoverflow.com/questions/55773033/loop-over-biginteger-values-using-foreach-in-kotlin
```Kotlin
class BigIntegerRange(
        override val start: BigInteger,
        override val endInclusive: BigInteger
) : ClosedRange<BigInteger>, Iterable<BigInteger> {
    override operator fun iterator(): Iterator<BigInteger> = BigIntegerRangeIterator(this)
}

class BigIntegerRangeIterator(
        private val range: ClosedRange<BigInteger>
) : Iterator<BigInteger> {
    private var current = range.start

    override fun hasNext(): Boolean =
            current <= range.endInclusive

    override fun next(): BigInteger {
        if (!hasNext()) {
            throw NoSuchElementException()
        }
        return current++
    }
}

operator fun BigInteger.rangeTo(other: BigInteger) = BigIntegerRange(this, other)
```

**Comment by tnakai11** [comment]
@FGKN0263 Thanks!
